version: 0.2

env:
  variables:
    AWS_REGION: eu-central-1
    STACK_NAME: address-splitter
    STAGE: dev

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Install phase (deps handled in Docker build)"
  pre_build:
    commands:
      - echo "Running tests (placeholder)"
      - python -m compileall backend/src || true
  build:
    commands:
      - echo "BuildDeploy (CodeBuild)"
      - chmod +x scripts/codebuild_deploy.sh
      - ./scripts/codebuild_deploy.sh

artifacts:
  files:
    - '**/*'
