version: 0.2

env:
  variables:
    AWS_REGION: eu-central-1
    STACK_NAME: address-splitter
    STAGE: dev

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install -r backend/requirements.txt || true
  pre_build:
    commands:
      - echo "Running tests (placeholder)"
      - python -m compileall backend/src || true
  build:
    commands:
      - echo "Deploying CloudFormation stack"
      - aws cloudformation deploy \
          --region "$AWS_REGION" \
          --stack-name "$STACK_NAME-$STAGE" \
          --template-file infra/cloudformation/main.yaml \
          --capabilities CAPABILITY_NAMED_IAM \
          --no-fail-on-empty-changeset
      - echo "Fetching outputs"
      - export FRONTEND_BUCKET=$(aws cloudformation describe-stacks --region "$AWS_REGION" --stack-name "$STACK_NAME-$STAGE" --query "Stacks[0].Outputs[?OutputKey=='FrontendBucketName'].OutputValue" --output text)
      - export DISTRIBUTION_ID=$(aws cloudformation describe-stacks --region "$AWS_REGION" --stack-name "$STACK_NAME-$STAGE" --query "Stacks[0].Outputs[?OutputKey=='CloudFrontDistributionId'].OutputValue" --output text)
      - echo "Syncing frontend to S3: $FRONTEND_BUCKET"
      - aws s3 sync frontend/ "s3://$FRONTEND_BUCKET/" --delete
      - echo "Invalidating CloudFront: $DISTRIBUTION_ID"
      - aws cloudfront create-invalidation --distribution-id "$DISTRIBUTION_ID" --paths "/*"

artifacts:
  files:
    - '**/*'
